services:
  pdf-ai:
    build: .
    container_name: pdfai
    ports:
      - "3024:8000"  # Maps FastAPI's internal port 8000 to host 3024
    volumes:
      - ./data:/app/data
      - ./faiss_index:/app/faiss_index
    restart: unless-stopped
