services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - /mnt/sec/apps/ollama/data:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    command: /bin/bash -c "ollama pull mistral && tail -f /dev/null"  # Pull the model when the container starts

  pdfai:
    image: ghcr.io/therepos/pdfai-b:latest
    container_name: pdfai
    restart: unless-stopped
    depends_on:
      - ollama  # Ensure Ollama starts first
    environment:
      - OLLAMA_HOST=http://ollama:11434  # Ensure PDF-AI can talk to Ollama
      - OLLAMA_MODEL=mistral  # Set the model dynamically
    volumes:
      - /mnt/sec/apps/pdfai/data:/app/data
      - /mnt/sec/apps/pdfai/faiss_index:/app/faiss_index
    ports:
      - "3024:8000"  # Expose the PDF-AI API
