services:
  pdfai:
    image: ghcr.io/therepos/pdfai-b:latest
    container_name: pdfai
    restart: unless-stopped
    environment:
      - OLLAMA_SERVICE=${OLLAMA_SERVICE:-auto_detect}  # Auto-detect service name
      - OLLAMA_MODEL=mistral  # Default model
    volumes:
      - /mnt/sec/apps/pdfai/data:/app/data
      - /mnt/sec/apps/pdfai/faiss_index:/app/faiss_index
    ports:
      - "3024:8000"
    networks:
      - ${OLLAMA_NETWORK:-bridge}  # Auto-detect network or use default

networks:
  bridge:
    external: true  # Default network fallback
