services:
  pdfai:
    image: ghcr.io/therepos/pdfai-b:latest
    container_name: pdfai
    restart: unless-stopped
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=mistral  # Default model
    volumes:
      - /mnt/sec/apps/pdfai/export:/app/export
      - /mnt/sec/apps/pdfai/faiss_index:/app/faiss_index
    ports:
      - "3024:8000"
