  pdfai:
    image: ghcr.io/therepos/pdfai:latest
    container_name: pdfai
    restart: unless-stopped
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=mistral  # Default model
      - SMTP_HOST=smtp.sendgrid.net
      - SMTP_PORT=587
      - SMTP_USER=noreply@threeminuteslab.com
      - SMTP_PASS=${SMTP_PASS}
    volumes:
      - /mnt/sec/apps/pdfai/data:/app/data
      - /mnt/sec/apps/pdfai/export:/app/export
      - /mnt/sec/apps/pdfai/src:/app/src  # <-- live-editable code
    ports:
      - "3024:8000"